title: Sen Li's Homepage
page-top-title: XIE JIAHONG
top-section-bg-text: STUDENT OF MPU
home-subtitle: XIE JIAHONG&ensp;|&ensp;谢佳宏(P2519852)
copyright-text: '&copy; XIE JIAOHNG 2023-2025. All Rights Reserved.'
